[package]
name = "procedural-terrain"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
image = "0.24.8"
nalgebra = "0.32.3"
noise = "0.8.2"
rand = "0.8.5"
rayon = "1.7.0"
indicatif = "0.17.5"
anyhow = "1.0"
winit = "0.30"
env_logger = "0.10"
log = "0.4"
wgpu = "27.0.0"
pollster = "0.3"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3